version: 0.2

phases:
  pre_build:
    commands:
      - echo Install Dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  # post_build:
  #   commands:

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
